### ISSUE TITLE
Known incompatible with ruby 3.1 -- YAML load of symbols

### ISSUE THREAD

**Issue by jrochkind** [samvera/browse-everything#389]
While b-e may not be tested with ruby 3.0 (not sure), in fact I'm using it with ruby 3.0 just fine (doesn't mean all codepaths are clean necessarily). 

But trying to upgrade my app to ruby 3.1, I found out that b-e is definitely not compatible with ruby 3.1. 

Got an `ActionView::Template::Error (wrong number of arguments (given 2, expected 1))`, on:

```
ruby-3.1.2/lib/ruby/3.1.0/psych.rb:323:in `safe_load'
browse-everything (1.1.2) lib/browse_everything.rb:58:in `configure'
browse-everything (1.1.2) lib/browse_everything.rb:78:in `config'
browse-everything (1.1.2) lib/browse_everything/browser.rb:13:in `initialize'
browse-everything (1.1.2) app/services/browser_factory.rb:6:in `new'
browse-everything (1.1.2) app/services/browser_factory.rb:6:in `build'
browse-everything (1.1.2) app/controllers/browse_everything_controller.rb:123:in `browser'
browse-everything (1.1.2) app/controllers/browse_everything_controller.rb:128:in `browser'
```

https://github.com/samvera/browse-everything/blob/69a22a5ea17ef0f159987a904e5935bd50e59598/lib/browse_everything.rb#L58

I'm not sure what the second arg to safe_load in `YAML.safe_load(config_file_template.result, [Symbol])` is trying to do? But looks like a second arg is no longer supported?

Here's the commit that introduced it, with commit message "Allow browse_everything_providers.yml to contain symbols"

https://github.com/samvera/browse-everything/commit/11f01548a3092b9a43a0fa8f960f470ea565838d

It looks like the second arg is labelled `legacy_permitted_classes` in the docs: https://ruby-doc.org/stdlib-2.6.1/libdoc/psych/rdoc/Psych.html#method-c-safe_load

It may be that in ruby 3.1, you can no longer do a `YAML.safe_load` that returns deserialized data with symbols?  If browse_everything is depending on that behavior, that could be a somewhat more painful thing to fix.

**Comment by jrochkind** [comment]
Oddly, ruby stdlib docs at 3.1.0 still suggest that that YAML.safe_load supports a second argument for `permitted_classes`. 

https://ruby-doc.org/stdlib-3.1.2/libdoc/psych/rdoc/Psych.html#method-c-safe_load

Aha, but it's as a keyword argument `permitted_classes:` rather than a second positional arg. 

So this is at least easier to fix while keeping semantics... although maybe a bit confusing to keep working in multiple ruby versions. 

Although actually it looks like `permitted_classes:` keyword is supported all the way back to ruby 2.6....  https://ruby-doc.org/stdlib-3.1.2/libdoc/psych/rdoc/Psych.html#method-c-safe_load

Browse-everything README claims that ruby 2.4-2.7 are supported. Ruby 2.4 is of course EOL by ruby, but.. also sadly did not yet support the `permitted_classes:` keyword. https://ruby-doc.org/stdlib-2.4.10/libdoc/psych/rdoc/Psych.html#method-c-safe_load . So we'd either need to stop support such old ruby, or put in a conditional to call `safe_load` differently depending on ruby version. 

It looks to me like 2.6 is the first ruby to support the `permitted_classes` keyword that we would need to use for ruby 3.1 compat.
